config/routes.rb
AppMysql::Application.routes.draw do
  resources :departements

  resources :regions do
    resources :departements    
  end

  resources :articles

end

app/models/article.rb
# == Schema Information
# Schema version: 20101110121455
#
# Table name: articles
#
#  id          :integer(4)      not null, primary key
#  nom         :string(255)
#  commentaire :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Article < ActiveRecord::Base
end

app/models/departement.rb
# == Schema Information
# Schema version: 20101110121455
#
# Table name: departements
#
#  id         :integer(4)      not null, primary key
#  region_id  :integer(4)
#  nom        :string(255)
#  code       :string(255)
#  nc         :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Departement < ActiveRecord::Base
  belongs_to :region
end

app/models/region.rb
# == Schema Information
# Schema version: 20101110121455
#
# Table name: regions
#
#  id         :integer(4)      not null, primary key
#  nom        :string(255)
#  code       :string(255)
#  nc         :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Region < ActiveRecord::Base
  has_many :departements
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/departements_controller.rb
class DepartementsController < ApplicationController
  # GET /departements
  # GET /departements.xml
  def index
    @region = Region.find_by_id(params[:region_id])
    @departements = @region ? @region.departements : Departement.all
    #@departements = Departement.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @departements }
    end
  end

  # GET /departements/1
  # GET /departements/1.xml
  def show
    @departement = Departement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @departement }
    end
  end

  # GET /departements/new
  # GET /departements/new.xml
  def new
    @departement = Departement.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @departement }
    end
  end

  # GET /departements/1/edit
  def edit
    @departement = Departement.find(params[:id])
  end

  # POST /departements
  # POST /departements.xml
  def create
    @departement = Departement.new(params[:departement])

    respond_to do |format|
      if @departement.save
        format.html { redirect_to(@departement, :notice => 'Departement was successfully created.') }
        format.xml  { render :xml => @departement, :status => :created, :location => @departement }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @departement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /departements/1
  # PUT /departements/1.xml
  def update
    @departement = Departement.find(params[:id])

    respond_to do |format|
      if @departement.update_attributes(params[:departement])
        format.html { redirect_to(@departement, :notice => 'Departement was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @departement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /departements/1
  # DELETE /departements/1.xml
  def destroy
    @departement = Departement.find(params[:id])
    @departement.destroy

    respond_to do |format|
      format.html { redirect_to(departements_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  # GET /regions
  # GET /regions.xml
  def index
    @regions = Region.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @regions }
    end
  end

  # GET /regions/1
  # GET /regions/1.xml
  def show
    @region = Region.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @region }
    end
  end

  # GET /regions/new
  # GET /regions/new.xml
  def new
    @region = Region.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @region }
    end
  end

  # GET /regions/1/edit
  def edit
    @region = Region.find(params[:id])
  end

  # POST /regions
  # POST /regions.xml
  def create
    @region = Region.new(params[:region])

    respond_to do |format|
      if @region.save
        format.html { redirect_to(@region, :notice => 'Region was successfully created.') }
        format.xml  { render :xml => @region, :status => :created, :location => @region }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @region.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /regions/1
  # PUT /regions/1.xml
  def update
    @region = Region.find(params[:id])

    respond_to do |format|
      if @region.update_attributes(params[:region])
        format.html { redirect_to(@region, :notice => 'Region was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @region.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.xml
  def destroy
    @region = Region.find(params[:id])
    @region.destroy

    respond_to do |format|
      format.html { redirect_to(regions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/departements_helper.rb
module DepartementsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :commentaire %><br />
    <%= f.text_field :commentaire %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Nom</th>
    <th>Commentaire</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.nom %></td>
    <td><%= article.commentaire %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nom:</b>
  <%= @article.nom %>
</p>

<p>
  <b>Commentaire:</b>
  <%= @article.commentaire %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/departements/_form.html.erb
<%= form_for(@departement) do |f| %>
  <% if @departement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@departement.errors.count, "error") %> prohibited this departement from being saved:</h2>

      <ul>
      <% @departement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :region_id %><br />
    <%= f.text_field :region_id %>
  </div>
  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :nc %><br />
    <%= f.text_field :nc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departements/edit.html.erb
<h1>Editing departement</h1>

<%= render 'form' %>

<%= link_to 'Show', @departement %> |
<%= link_to 'Back', departements_path %>

app/views/departements/index.html.erb
<h1>Listing departements</h1>

<table>
  <tr>
    <th>Region</th>
    <th>Nom</th>
    <th>Code</th>
    <th>Nc</th>
    <th>Code region</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @departements.each do |departement| %>
  <tr>
    <td><%= departement.region_id %></td>
    <td><%= departement.nom %></td>
    <td><%= departement.code %></td>
    <td><%= departement.nc %></td>
    <td><%= link_to 'Show', departement %></td>
    <td><%= link_to 'Edit', edit_departement_path(departement) %></td>
    <td><%= link_to 'Destroy', departement, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Departement', new_departement_path %>

app/views/departements/new.html.erb
<h1>New departement</h1>

<%= render 'form' %>

<%= link_to 'Back', departements_path %>

app/views/departements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Region:</b>
  <%= @departement.region_id %>
</p>

<p>
  <b>Nom:</b>
  <%= @departement.nom %>
</p>

<p>
  <b>Code:</b>
  <%= @departement.code %>
</p>

<p>
  <b>Nc:</b>
  <%= @departement.nc %>
</p>


<%= link_to 'Edit', edit_departement_path(@departement) %> |
<%= link_to 'Back', departements_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppMysql</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>
<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/regions/_form.html.erb
<%= form_for(@region) do |f| %>
  <% if @region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
      <% @region.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :nc %><br />
    <%= f.text_field :nc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regions/edit.html.erb
<h1>Editing region</h1>

<%= render 'form' %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>

app/views/regions/index.html.erb
<h1>Listing regions</h1>

<table>
  <tr>
    <th>Nom</th>
    <th>Code</th>
    <th>Nc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @regions.each do |region| %>
  <tr>
    <td><%= region.nom %></td>
    <td><%= region.code %></td>
    <td><%= region.nc %></td>
    <td><%= link_to 'Show', region %></td>
    <td><%= link_to 'Edit', edit_region_path(region) %></td>
    <td><%= link_to 'Destroy', region, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Region', new_region_path %>

app/views/regions/new.html.erb
<h1>New region</h1>

<%= render 'form' %>

<%= link_to 'Back', regions_path %>

app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nom:</b>
  <%= @region.nom %>
</p>

<p>
  <b>Code:</b>
  <%= @region.code %>
</p>

<p>
  <b>Nc:</b>
  <%= @region.nc %>
</p>


<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Back', regions_path %>